
-- Regions (7 official zones)
INSERT INTO regions(code,name) VALUES
 ('NO','Noroeste'),('NE','Noreste'),('OC','Occidente'),
 ('BA','Bajío'),('CE','Centro'),('SU','Sur'),('SE','Sureste')
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name;

-- 302 stores (151 fisicas x 2 marcas)
INSERT INTO stores(code,name,brand,region_code,address) VALUES
('PH-CENTRO-LAN','Palacio Centro - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-CENTRO-YSL','Palacio Centro - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-COYOAC-LAN','Palacio Coyoacán - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-COYOAC-YSL','Palacio Coyoacán - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-DURANG-LAN','Palacio Durango - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-DURANG-YSL','Palacio Durango - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-GUADAL-LAN','Palacio Guadalajara - LANCOME','lancome','OC','Guadalajara, Jalisco'),
('PH-GUADAL-YSL','Palacio Guadalajara - YSL','ysl','OC','Guadalajara, Jalisco'),
('PH-INTERL-LAN','Palacio Interlomas - LANCOME','lancome','CE','Huixquilucan, Estado de México'),
('PH-INTERL-YSL','Palacio Interlomas - YSL','ysl','CE','Huixquilucan, Estado de México'),
('PH-LEON-LAN','Palacio León - LANCOME','lancome','BA','León, Guanajuato'),
('PH-LEON-YSL','Palacio León - YSL','ysl','BA','León, Guanajuato'),
('PH-MONTER-LAN','Palacio Monterrey - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('PH-MONTER-YSL','Palacio Monterrey - YSL','ysl','NE','Monterrey, Nuevo León'),
('PH-PERISU-LAN','Palacio Perisur - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-PERISU-YSL','Palacio Perisur - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-POLANC-LAN','Palacio Polanco - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-POLANC-YSL','Palacio Polanco - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-PUEBLA-LAN','Palacio Puebla - LANCOME','lancome','CE','Puebla, Puebla'),
('PH-PUEBLA-YSL','Palacio Puebla - YSL','ysl','CE','Puebla, Puebla'),
('PH-QUERET-LAN','Palacio Querétaro - LANCOME','lancome','BA','Querétaro, Querétaro'),
('PH-QUERET-YSL','Palacio Querétaro - YSL','ysl','BA','Querétaro, Querétaro'),
('PH-SANTA--LAN','Palacio Santa Fe - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-SANTA--YSL','Palacio Santa Fe - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-SATELI-LAN','Palacio Satélite - LANCOME','lancome','CE','Naucalpan, Estado de México'),
('PH-SATELI-YSL','Palacio Satélite - YSL','ysl','CE','Naucalpan, Estado de México'),
('PH-VERACR-LAN','Palacio Veracruz - LANCOME','lancome','SE','Veracruz, Veracruz'),
('PH-VERACR-YSL','Palacio Veracruz - YSL','ysl','SE','Veracruz, Veracruz'),
('PH-VILLAH-LAN','Palacio Villahermosa - LANCOME','lancome','SE','Villahermosa, Tabasco'),
('PH-VILLAH-YSL','Palacio Villahermosa - YSL','ysl','SE','Villahermosa, Tabasco'),
('PH-CANCUN-LAN','La Boutique Palacio Cancún - LANCOME','lancome','SE','Cancún, Quintana Roo'),
('PH-CANCUN-YSL','La Boutique Palacio Cancún - YSL','ysl','SE','Cancún, Quintana Roo'),
('PH-ACOXPA-LAN','La Boutique Palacio Acoxpa - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('PH-ACOXPA-YSL','La Boutique Palacio Acoxpa - YSL','ysl','CE','Ciudad de México, CDMX'),
('PH-ACAPUL-LAN','La Boutique Palacio Acapulco - LANCOME','lancome','SU','Acapulco, Guerrero'),
('PH-ACAPUL-YSL','La Boutique Palacio Acapulco - YSL','ysl','SU','Acapulco, Guerrero'),
('LIV-GALERIAS-LAN','Liverpool Galerías Cuernavaca - LANCOME','lancome','CE','Cuernavaca, Morelos'),
('LIV-GALERIAS-YSL','Liverpool Galerías Cuernavaca - YSL','ysl','CE','Cuernavaca, Morelos'),
('LIV-ACAPULCO-LAN','Liverpool Acapulco La Isla - LANCOME','lancome','SU','Acapulco, Guerrero'),
('LIV-ACAPULCO-YSL','Liverpool Acapulco La Isla - YSL','ysl','SU','Acapulco, Guerrero'),
('LIV-AGS-ALTA-LAN','Liverpool Ags. Altaria - LANCOME','lancome','BA','Aguascalientes, Aguascalientes'),
('LIV-AGS-ALTA-YSL','Liverpool Ags. Altaria - YSL','ysl','BA','Aguascalientes, Aguascalientes'),
('LIV-ALTABRIS-LAN','Liverpool Altabrisa - LANCOME','lancome','SE','Mérida, Yucatán'),
('LIV-ALTABRIS-YSL','Liverpool Altabrisa - YSL','ysl','SE','Mérida, Yucatán'),
('LIV-ANDARES-LAN','Liverpool Andares - LANCOME','lancome','OC','Zapopan, Jalisco'),
('LIV-ANDARES-YSL','Liverpool Andares - YSL','ysl','OC','Zapopan, Jalisco'),
('LIV-ANGELOPO-LAN','Liverpool Angelópolis - LANCOME','lancome','CE','Puebla, Puebla'),
('LIV-ANGELOPO-YSL','Liverpool Angelópolis - YSL','ysl','CE','Puebla, Puebla'),
('LIV-ANTEA-LAN','Liverpool Antea - LANCOME','lancome','BA','Querétaro, Querétaro'),
('LIV-ANTEA-YSL','Liverpool Antea - YSL','ysl','BA','Querétaro, Querétaro'),
('LIV-ATLIXCO-LAN','Liverpool Atlixco - LANCOME','lancome','CE','Atlixco, Puebla'),
('LIV-ATLIXCO-YSL','Liverpool Atlixco - YSL','ysl','CE','Atlixco, Puebla'),
('LIV-CANCUN-LAN','Liverpool Cancún - LANCOME','lancome','SE','Cancún, Quintana Roo'),
('LIV-CANCUN-YSL','Liverpool Cancún - YSL','ysl','SE','Cancún, Quintana Roo'),
('LIV-CD-JUARE-LAN','Liverpool Cd. Juárez Las Misiones - LANCOME','lancome','NO','Ciudad Juárez, Chihuahua'),
('LIV-CD-JUARE-YSL','Liverpool Cd. Juárez Las Misiones - YSL','ysl','NO','Ciudad Juárez, Chihuahua'),
('LIV-CENTRO-LAN','Liverpool Centro - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-CENTRO-YSL','Liverpool Centro - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-CIUDAD-V-LAN','Liverpool Ciudad Victoria - LANCOME','lancome','NE','Ciudad Victoria, Tamaulipas'),
('LIV-CIUDAD-V-YSL','Liverpool Ciudad Victoria - YSL','ysl','NE','Ciudad Victoria, Tamaulipas'),
('LIV-COATZACO-LAN','Liverpool Coatzacoalcos - LANCOME','lancome','SE','Coatzacoalcos, Veracruz'),
('LIV-COATZACO-YSL','Liverpool Coatzacoalcos - YSL','ysl','SE','Coatzacoalcos, Veracruz'),
('LIV-COLIMA-LAN','Liverpool Colima - LANCOME','lancome','OC','Colima, Colima'),
('LIV-COLIMA-YSL','Liverpool Colima - YSL','ysl','OC','Colima, Colima'),
('LIV-CULIACAN-LAN','Liverpool Culiacán - LANCOME','lancome','NO','Culiacán, Sinaloa'),
('LIV-CULIACAN-YSL','Liverpool Culiacán - YSL','ysl','NO','Culiacán, Sinaloa'),
('LIV-DURANGO-LAN','Liverpool Durango - LANCOME','lancome','NO','Durango, Durango'),
('LIV-DURANGO-YSL','Liverpool Durango - YSL','ysl','NO','Durango, Durango'),
('LIV-FRESNILL-LAN','Liverpool Fresnillo - LANCOME','lancome','BA','Fresnillo, Zacatecas'),
('LIV-FRESNILL-YSL','Liverpool Fresnillo - YSL','ysl','BA','Fresnillo, Zacatecas'),
('LIV-GALERIAS2-LAN','Liverpool Galerías Atizapán - LANCOME','lancome','CE','Atizapán, Estado de México'),
('LIV-GALERIAS2-YSL','Liverpool Galerías Atizapán - YSL','ysl','CE','Atizapán, Estado de México'),
('LIV-GALERIAS3-LAN','Liverpool Galerías Campeche - LANCOME','lancome','SE','Campeche, Campeche'),
('LIV-GALERIAS3-YSL','Liverpool Galerías Campeche - YSL','ysl','SE','Campeche, Campeche'),
('LIV-GALERIAS4-LAN','Liverpool Galerías Celaya - LANCOME','lancome','BA','Celaya, Guanajuato'),
('LIV-GALERIAS4-YSL','Liverpool Galerías Celaya - YSL','ysl','BA','Celaya, Guanajuato'),
('LIV-GALERIAS5-LAN','Liverpool Galerías Hermosillo - LANCOME','lancome','NO','Hermosillo, Sonora'),
('LIV-GALERIAS5-YSL','Liverpool Galerías Hermosillo - YSL','ysl','NO','Hermosillo, Sonora'),
('LIV-GALERIAS6-LAN','Liverpool Galerías Monterrey - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('LIV-GALERIAS6-YSL','Liverpool Galerías Monterrey - YSL','ysl','NE','Monterrey, Nuevo León'),
('LIV-GALERIAS7-LAN','Liverpool Galerías Mérida - LANCOME','lancome','SE','Mérida, Yucatán'),
('LIV-GALERIAS7-YSL','Liverpool Galerías Mérida - YSL','ysl','SE','Mérida, Yucatán'),
('LIV-GALERIAS8-LAN','Liverpool Galerías Saltillo - LANCOME','lancome','NE','Saltillo, Coahuila'),
('LIV-GALERIAS8-YSL','Liverpool Galerías Saltillo - YSL','ysl','NE','Saltillo, Coahuila'),
('LIV-GALERIAS9-LAN','Liverpool Galerías Tabasco - LANCOME','lancome','SE','Villahermosa, Tabasco'),
('LIV-GALERIAS9-YSL','Liverpool Galerías Tabasco - YSL','ysl','SE','Villahermosa, Tabasco'),
('LIV-GALERIAS10-LAN','Liverpool Galerías Zacatecas - LANCOME','lancome','BA','Zacatecas, Zacatecas'),
('LIV-GALERIAS10-YSL','Liverpool Galerías Zacatecas - YSL','ysl','BA','Zacatecas, Zacatecas'),
('LIV-HERMOSIL-LAN','Liverpool Hermosillo Encinas - LANCOME','lancome','NO','Hermosillo, Sonora'),
('LIV-HERMOSIL-YSL','Liverpool Hermosillo Encinas - YSL','ysl','NO','Hermosillo, Sonora'),
('LIV-LA-PAZ-LAN','Liverpool La Paz - LANCOME','lancome','NO','La Paz, Baja California Sur'),
('LIV-LA-PAZ-YSL','Liverpool La Paz - YSL','ysl','NO','La Paz, Baja California Sur'),
('LIV-MAZATLAN-LAN','Liverpool Mazatlán Marina - LANCOME','lancome','NO','Mazatlán, Sinaloa'),
('LIV-MAZATLAN-YSL','Liverpool Mazatlán Marina - YSL','ysl','NO','Mazatlán, Sinaloa'),
('LIV-MEXICALI-LAN','Liverpool Mexicali - LANCOME','lancome','NO','Mexicali, Baja California'),
('LIV-MEXICALI-YSL','Liverpool Mexicali - YSL','ysl','NO','Mexicali, Baja California'),
('LIV-MONTERRE-LAN','Liverpool Monterrey Esfera - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('LIV-MONTERRE-YSL','Liverpool Monterrey Esfera - YSL','ysl','NE','Monterrey, Nuevo León'),
('LIV-MORELIA--LAN','Liverpool Morelia Altozano - LANCOME','lancome','OC','Morelia, Michoacán'),
('LIV-MORELIA--YSL','Liverpool Morelia Altozano - YSL','ysl','OC','Morelia, Michoacán'),
('LIV-MERIDA-L-LAN','Liverpool Mérida la Isla Cabo Norte - LANCOME','lancome','SE','Mérida, Yucatán'),
('LIV-MERIDA-L-YSL','Liverpool Mérida la Isla Cabo Norte - YSL','ysl','SE','Mérida, Yucatán'),
('LIV-PACHUCA-LAN','Liverpool Pachuca - LANCOME','lancome','CE','Pachuca, Hidalgo'),
('LIV-PACHUCA-YSL','Liverpool Pachuca - YSL','ysl','CE','Pachuca, Hidalgo'),
('LIV-PARQUE-L-LAN','Liverpool Parque Las Antenas - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-PARQUE-L-YSL','Liverpool Parque Las Antenas - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-PARQUE-P-LAN','Liverpool Parque Puebla - LANCOME','lancome','CE','Puebla, Puebla'),
('LIV-PARQUE-P-YSL','Liverpool Parque Puebla - YSL','ysl','CE','Puebla, Puebla'),
('LIV-PASEO-IN-LAN','Liverpool Paseo Interlomas - LANCOME','lancome','CE','Huixquilucan, Estado de México'),
('LIV-PASEO-IN-YSL','Liverpool Paseo Interlomas - YSL','ysl','CE','Huixquilucan, Estado de México'),
('LIV-PASEO-IN2-LAN','Liverpool Paseo Interlomas (2) - LANCOME','lancome','CE','Huixquilucan, Estado de México'),
('LIV-PASEO-IN2-YSL','Liverpool Paseo Interlomas (2) - YSL','ysl','CE','Huixquilucan, Estado de México'),
('LIV-PASEO-QU-LAN','Liverpool Paseo Querétaro - LANCOME','lancome','BA','Querétaro, Querétaro'),
('LIV-PASEO-QU-YSL','Liverpool Paseo Querétaro - YSL','ysl','BA','Querétaro, Querétaro'),
('LIV-SALINA-C-LAN','Liverpool Salina Cruz - LANCOME','lancome','SU','Salina Cruz, Oaxaca'),
('LIV-SALINA-C-YSL','Liverpool Salina Cruz - YSL','ysl','SU','Salina Cruz, Oaxaca'),
('LIV-SAN-LUIS-LAN','Liverpool San Luis Potosí - LANCOME','lancome','BA','San Luis Potosí, San Luis Potosí'),
('LIV-SAN-LUIS-YSL','Liverpool San Luis Potosí - YSL','ysl','BA','San Luis Potosí, San Luis Potosí'),
('LIV-TEPIC-LAN','Liverpool Tepic - LANCOME','lancome','OC','Tepic, Nayarit'),
('LIV-TEPIC-YSL','Liverpool Tepic - YSL','ysl','OC','Tepic, Nayarit'),
('LIV-TLAXCALA-LAN','Liverpool Tlaxcala - LANCOME','lancome','CE','Tlaxcala, Tlaxcala'),
('LIV-TLAXCALA-YSL','Liverpool Tlaxcala - YSL','ysl','CE','Tlaxcala, Tlaxcala'),
('LIV-TOREO-LAN','Liverpool Toreo - LANCOME','lancome','CE','Naucalpan, Estado de México'),
('LIV-TOREO-YSL','Liverpool Toreo - YSL','ysl','CE','Naucalpan, Estado de México'),
('LIV-TUXTLA-LAN','Liverpool Tuxtla - LANCOME','lancome','SU','Tuxtla Gutiérrez, Chiapas'),
('LIV-TUXTLA-YSL','Liverpool Tuxtla - YSL','ysl','SU','Tuxtla Gutiérrez, Chiapas'),
('LIV-TUXTLA-O-LAN','Liverpool Tuxtla Oriente - LANCOME','lancome','SU','Tuxtla Gutiérrez, Chiapas'),
('LIV-TUXTLA-O-YSL','Liverpool Tuxtla Oriente - YSL','ysl','SU','Tuxtla Gutiérrez, Chiapas'),
('LIV-ZAMORA-LAN','Liverpool Zamora - LANCOME','lancome','OC','Zamora, Michoacán'),
('LIV-ZAMORA-YSL','Liverpool Zamora - YSL','ysl','OC','Zamora, Michoacán'),
('LIV-AGUASCAL-LAN','Liverpool Aguascalientes Villasunción - LANCOME','lancome','BA','Aguascalientes, Aguascalientes'),
('LIV-AGUASCAL-YSL','Liverpool Aguascalientes Villasunción - YSL','ysl','BA','Aguascalientes, Aguascalientes'),
('LIV-CD-JARDI-LAN','Liverpool Cd. Jardín - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-CD-JARDI-YSL','Liverpool Cd. Jardín - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-CD-OBREG-LAN','Liverpool Cd. Obregón - LANCOME','lancome','NO','Ciudad Obregón, Sonora'),
('LIV-CD-OBREG-YSL','Liverpool Cd. Obregón - YSL','ysl','NO','Ciudad Obregón, Sonora'),
('LIV-CD-DEL-C-LAN','Liverpool Cd. del Carmen - LANCOME','lancome','SE','Ciudad del Carmen, Campeche'),
('LIV-CD-DEL-C-YSL','Liverpool Cd. del Carmen - YSL','ysl','SE','Ciudad del Carmen, Campeche'),
('LIV-CHETUMAL-LAN','Liverpool Chetumal - LANCOME','lancome','SE','Chetumal, Quintana Roo'),
('LIV-CHETUMAL-YSL','Liverpool Chetumal - YSL','ysl','SE','Chetumal, Quintana Roo'),
('LIV-CHIHUAHU-LAN','Liverpool Chihuahua Fashion Mall - LANCOME','lancome','NO','Chihuahua, Chihuahua'),
('LIV-CHIHUAHU-YSL','Liverpool Chihuahua Fashion Mall - YSL','ysl','NO','Chihuahua, Chihuahua'),
('LIV-CUAUTLA-LAN','Liverpool Cuautla - LANCOME','lancome','CE','Cuautla, Morelos'),
('LIV-CUAUTLA-YSL','Liverpool Cuautla - YSL','ysl','CE','Cuautla, Morelos'),
('LIV-GALERIAS11-LAN','Liverpool Galerías Chilpancingo - LANCOME','lancome','SU','Chilpancingo, Guerrero'),
('LIV-GALERIAS11-YSL','Liverpool Galerías Chilpancingo - YSL','ysl','SU','Chilpancingo, Guerrero'),
('LIV-GALERIAS12-LAN','Liverpool Galerías Coapa - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-GALERIAS12-YSL','Liverpool Galerías Coapa - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-GALERIAS13-LAN','Liverpool Galerías Guadalajara - LANCOME','lancome','OC','Guadalajara, Jalisco'),
('LIV-GALERIAS13-YSL','Liverpool Galerías Guadalajara - YSL','ysl','OC','Guadalajara, Jalisco'),
('LIV-GALERIAS14-LAN','Liverpool Galerías Querétaro - LANCOME','lancome','BA','Querétaro, Querétaro'),
('LIV-GALERIAS14-YSL','Liverpool Galerías Querétaro - YSL','ysl','BA','Querétaro, Querétaro'),
('LIV-GALERIAS15-LAN','Liverpool Galerías Serdán - LANCOME','lancome','CE','Puebla, Puebla'),
('LIV-GALERIAS15-YSL','Liverpool Galerías Serdán - YSL','ysl','CE','Puebla, Puebla'),
('LIV-IRAPUATO-LAN','Liverpool Irapuato Plaza Cibeles - LANCOME','lancome','BA','Irapuato, Guanajuato'),
('LIV-IRAPUATO-YSL','Liverpool Irapuato Plaza Cibeles - YSL','ysl','BA','Irapuato, Guanajuato'),
('LIV-LA-PERLA-LAN','Liverpool La Perla - LANCOME','lancome','OC','Zapopan, Jalisco'),
('LIV-LA-PERLA-YSL','Liverpool La Perla - YSL','ysl','OC','Zapopan, Jalisco'),
('LIV-LOS-MOCH-LAN','Liverpool Los Mochis - LANCOME','lancome','NO','Los Mochis, Sinaloa'),
('LIV-LOS-MOCH-YSL','Liverpool Los Mochis - YSL','ysl','NO','Los Mochis, Sinaloa'),
('LIV-MONTERRE2-LAN','Liverpool Monterrey Centro - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('LIV-MONTERRE2-YSL','Liverpool Monterrey Centro - YSL','ysl','NE','Monterrey, Nuevo León'),
('LIV-MONTERRE3-LAN','Liverpool Monterrey la Fe - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('LIV-MONTERRE3-YSL','Liverpool Monterrey la Fe - YSL','ysl','NE','Monterrey, Nuevo León'),
('LIV-MORELIA-2-LAN','Liverpool Morelia Las Américas - LANCOME','lancome','OC','Morelia, Michoacán'),
('LIV-MORELIA-2-YSL','Liverpool Morelia Las Américas - YSL','ysl','OC','Morelia, Michoacán'),
('LIV-OAXACA-LAN','Liverpool Oaxaca - LANCOME','lancome','SU','Oaxaca, Oaxaca'),
('LIV-OAXACA-YSL','Liverpool Oaxaca - YSL','ysl','SU','Oaxaca, Oaxaca'),
('LIV-OAXACA-P-LAN','Liverpool Oaxaca Plaza Bella - LANCOME','lancome','SU','Oaxaca, Oaxaca'),
('LIV-OAXACA-P-YSL','Liverpool Oaxaca Plaza Bella - YSL','ysl','SU','Oaxaca, Oaxaca'),
('LIV-ORIZABA-LAN','Liverpool Orizaba - LANCOME','lancome','SE','Orizaba, Veracruz'),
('LIV-ORIZABA-YSL','Liverpool Orizaba - YSL','ysl','SE','Orizaba, Veracruz'),
('LIV-SALAMANC-LAN','Liverpool Salamanca - LANCOME','lancome','BA','Salamanca, Guanajuato'),
('LIV-SALAMANC-YSL','Liverpool Salamanca - YSL','ysl','BA','Salamanca, Guanajuato'),
('LIV-SAN-LUIS2-LAN','Liverpool San Luis El Dorado - LANCOME','lancome','BA','San Luis Potosí, San Luis Potosí'),
('LIV-SAN-LUIS2-YSL','Liverpool San Luis El Dorado - YSL','ysl','BA','San Luis Potosí, San Luis Potosí'),
('LIV-TAMPICO-LAN','Liverpool Tampico - LANCOME','lancome','NE','Tampico, Tamaulipas'),
('LIV-TAMPICO-YSL','Liverpool Tampico - YSL','ysl','NE','Tampico, Tamaulipas'),
('LIV-TAMPICO--LAN','Liverpool Tampico Altama - LANCOME','lancome','NE','Tampico, Tamaulipas'),
('LIV-TAMPICO--YSL','Liverpool Tampico Altama - YSL','ysl','NE','Tampico, Tamaulipas'),
('LIV-TAPACHUL-LAN','Liverpool Tapachula - LANCOME','lancome','SU','Tapachula, Chiapas'),
('LIV-TAPACHUL-YSL','Liverpool Tapachula - YSL','ysl','SU','Tapachula, Chiapas'),
('LIV-TEPIC-CE-LAN','Liverpool Tepic Centro - LANCOME','lancome','OC','Tepic, Nayarit'),
('LIV-TEPIC-CE-YSL','Liverpool Tepic Centro - YSL','ysl','OC','Tepic, Nayarit'),
('LIV-TLALNEPA-LAN','Liverpool Tlalnepantla - LANCOME','lancome','CE','Tlalnepantla, Estado de México'),
('LIV-TLALNEPA-YSL','Liverpool Tlalnepantla - YSL','ysl','CE','Tlalnepantla, Estado de México'),
('LIV-TORREON-LAN','Liverpool Torreón - LANCOME','lancome','NE','Torreón, Coahuila'),
('LIV-TORREON-YSL','Liverpool Torreón - YSL','ysl','NE','Torreón, Coahuila'),
('LIV-ACAPULCO2-LAN','Liverpool Acapulco Galerías - LANCOME','lancome','SU','Acapulco, Guerrero'),
('LIV-ACAPULCO2-YSL','Liverpool Acapulco Galerías - YSL','ysl','SU','Acapulco, Guerrero'),
('LIV-CD-JUARE2-LAN','Liverpool Cd Juárez Rio Grande - LANCOME','lancome','NO','Ciudad Juárez, Chihuahua'),
('LIV-CD-JUARE2-YSL','Liverpool Cd Juárez Rio Grande - YSL','ysl','NO','Ciudad Juárez, Chihuahua'),
('LIV-CHIHUAHU2-LAN','Liverpool Chihuahua Presidentes - LANCOME','lancome','NO','Chihuahua, Chihuahua'),
('LIV-CHIHUAHU2-YSL','Liverpool Chihuahua Presidentes - YSL','ysl','NO','Chihuahua, Chihuahua'),
('LIV-COMITAN-LAN','Liverpool Comitán - LANCOME','lancome','SU','Comitán, Chiapas'),
('LIV-COMITAN-YSL','Liverpool Comitán - YSL','ysl','SU','Comitán, Chiapas'),
('LIV-GALERIAS16-LAN','Liverpool Galerías Insurgentes - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-GALERIAS16-YSL','Liverpool Galerías Insurgentes - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-GALERIAS17-LAN','Liverpool Galerías Puerto Vallarta - LANCOME','lancome','OC','Puerto Vallarta, Jalisco'),
('LIV-GALERIAS17-YSL','Liverpool Galerías Puerto Vallarta - YSL','ysl','OC','Puerto Vallarta, Jalisco'),
('LIV-GALERIAS18-LAN','Liverpool Galerías San Juan del Río - LANCOME','lancome','BA','San Juan del Río, Querétaro'),
('LIV-GALERIAS18-YSL','Liverpool Galerías San Juan del Río - YSL','ysl','BA','San Juan del Río, Querétaro'),
('LIV-GUANAJUA-LAN','Liverpool Guanajuato - LANCOME','lancome','BA','Guanajuato, Guanajuato'),
('LIV-GUANAJUA-YSL','Liverpool Guanajuato - YSL','ysl','BA','Guanajuato, Guanajuato'),
('LIV-LEON-ALT-LAN','Liverpool León Altacia - LANCOME','lancome','BA','León, Guanajuato'),
('LIV-LEON-ALT-YSL','Liverpool León Altacia - YSL','ysl','BA','León, Guanajuato'),
('LIV-MITIKAH-LAN','Liverpool Mitikah - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-MITIKAH-YSL','Liverpool Mitikah - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-MONTERRE4-LAN','Liverpool Monterrey Cumbres - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('LIV-MONTERRE4-YSL','Liverpool Monterrey Cumbres - YSL','ysl','NE','Monterrey, Nuevo León'),
('LIV-PLAYA-DE-LAN','Liverpool Playa del Carmen - LANCOME','lancome','SE','Playa del Carmen, Quintana Roo'),
('LIV-PLAYA-DE-YSL','Liverpool Playa del Carmen - YSL','ysl','SE','Playa del Carmen, Quintana Roo'),
('LIV-TEHUACAN-LAN','Liverpool Tehuacán - LANCOME','lancome','CE','Tehuacán, Puebla'),
('LIV-TEHUACAN-YSL','Liverpool Tehuacán - YSL','ysl','CE','Tehuacán, Puebla'),
('LIV-TUXPAN-LAN','Liverpool Tuxpan - LANCOME','lancome','SE','Tuxpan, Veracruz'),
('LIV-TUXPAN-YSL','Liverpool Tuxpan - YSL','ysl','SE','Tuxpan, Veracruz'),
('LIV-VILLAHER-LAN','Liverpool Villahermosa Crystal - LANCOME','lancome','SE','Villahermosa, Tabasco'),
('LIV-VILLAHER-YSL','Liverpool Villahermosa Crystal - YSL','ysl','SE','Villahermosa, Tabasco'),
('LIV-ECATEPEC-LAN','Liverpool Ecatepec - LANCOME','lancome','CE','Ecatepec, Estado de México'),
('LIV-ECATEPEC-YSL','Liverpool Ecatepec - YSL','ysl','CE','Ecatepec, Estado de México'),
('LIV-LEON-PLA-LAN','Liverpool León Plaza Mayor - LANCOME','lancome','BA','León, Guanajuato'),
('LIV-LEON-PLA-YSL','Liverpool León Plaza Mayor - YSL','ysl','BA','León, Guanajuato'),
('LIV-LINDAVIS-LAN','Liverpool Lindavista - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-LINDAVIS-YSL','Liverpool Lindavista - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-LINDAVIS2-LAN','Liverpool Lindavista (2) - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-LINDAVIS2-YSL','Liverpool Lindavista (2) - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-MAZATLAN2-LAN','Liverpool Mazatlán Centro - LANCOME','lancome','NO','Mazatlán, Sinaloa'),
('LIV-MAZATLAN2-YSL','Liverpool Mazatlán Centro - YSL','ysl','NO','Mazatlán, Sinaloa'),
('LIV-MONTERRE5-LAN','Liverpool Monterrey Valle - LANCOME','lancome','NE','Monterrey, Nuevo León'),
('LIV-MONTERRE5-YSL','Liverpool Monterrey Valle - YSL','ysl','NE','Monterrey, Nuevo León'),
('LIV-OBLATOS--LAN','Liverpool Oblatos Guadalajara - LANCOME','lancome','OC','Guadalajara, Jalisco'),
('LIV-OBLATOS--YSL','Liverpool Oblatos Guadalajara - YSL','ysl','OC','Guadalajara, Jalisco'),
('LIV-PUEBLA-C-LAN','Liverpool Puebla Crystal - LANCOME','lancome','CE','Puebla, Puebla'),
('LIV-PUEBLA-C-YSL','Liverpool Puebla Crystal - YSL','ysl','CE','Puebla, Puebla'),
('LIV-TEPEYAC-LAN','Liverpool Tepeyac - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-TEPEYAC-YSL','Liverpool Tepeyac - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-VERACRUZ-LAN','Liverpool Veracruz El Dorado - LANCOME','lancome','SE','Veracruz, Veracruz'),
('LIV-VERACRUZ-YSL','Liverpool Veracruz El Dorado - YSL','ysl','SE','Veracruz, Veracruz'),
('LIV-EXPRESS--LAN','Liverpool Express Cd Guzmán - LANCOME','lancome','OC','Ciudad Guzmán, Jalisco'),
('LIV-EXPRESS--YSL','Liverpool Express Cd Guzmán - YSL','ysl','OC','Ciudad Guzmán, Jalisco'),
('LIV-EXPRESS-2-LAN','Liverpool Express Lagos de Moreno - LANCOME','lancome','OC','Lagos de Moreno, Jalisco'),
('LIV-EXPRESS-2-YSL','Liverpool Express Lagos de Moreno - YSL','ysl','OC','Lagos de Moreno, Jalisco'),
('LIV-GALERIAS19-LAN','Liverpool Galerías Metepec - LANCOME','lancome','CE','Metepec, Estado de México'),
('LIV-GALERIAS19-YSL','Liverpool Galerías Metepec - YSL','ysl','CE','Metepec, Estado de México'),
('LIV-PARQUE-D-LAN','Liverpool Parque Delta - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-PARQUE-D-YSL','Liverpool Parque Delta - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-SAN-MIGU-LAN','Liverpool San Miguel de Allende - LANCOME','lancome','BA','San Miguel de Allende, Guanajuato'),
('LIV-SAN-MIGU-YSL','Liverpool San Miguel de Allende - YSL','ysl','BA','San Miguel de Allende, Guanajuato'),
('LIV-TLAQUEPA-LAN','Liverpool Tlaquepaque - LANCOME','lancome','OC','Tlaquepaque, Jalisco'),
('LIV-TLAQUEPA-YSL','Liverpool Tlaquepaque - YSL','ysl','OC','Tlaquepaque, Jalisco'),
('LIV-VERACRUZ2-LAN','Liverpool Veracruz Plaza Américas - LANCOME','lancome','SE','Veracruz, Veracruz'),
('LIV-VERACRUZ2-YSL','Liverpool Veracruz Plaza Américas - YSL','ysl','SE','Veracruz, Veracruz'),
('LIV-GALERIAS20-LAN','Liverpool Galerías Perinorte - LANCOME','lancome','CE','Cuautitlán Izcalli, Estado de México'),
('LIV-GALERIAS20-YSL','Liverpool Galerías Perinorte - YSL','ysl','CE','Cuautitlán Izcalli, Estado de México'),
('LIV-GALERIAS21-LAN','Liverpool Galerías Perinorte (2) - LANCOME','lancome','CE','Cuautitlán Izcalli, Estado de México'),
('LIV-GALERIAS21-YSL','Liverpool Galerías Perinorte (2) - YSL','ysl','CE','Cuautitlán Izcalli, Estado de México'),
('LIV-GRAN-PLA-LAN','Liverpool Gran Plaza - LANCOME','lancome','OC','Guadalajara, Jalisco'),
('LIV-GRAN-PLA-YSL','Liverpool Gran Plaza - YSL','ysl','OC','Guadalajara, Jalisco'),
('LIV-PERISUR-LAN','Liverpool Perisur - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-PERISUR-YSL','Liverpool Perisur - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-XALAPA-P-LAN','Liverpool Xalapa Plaza Américas - LANCOME','lancome','SE','Xalapa, Veracruz'),
('LIV-XALAPA-P-YSL','Liverpool Xalapa Plaza Américas - YSL','ysl','SE','Xalapa, Veracruz'),
('LIV-COATZACO2-LAN','Liverpool Coatzacoalcos Crystal - LANCOME','lancome','SE','Coatzacoalcos, Veracruz'),
('LIV-COATZACO2-YSL','Liverpool Coatzacoalcos Crystal - YSL','ysl','SE','Coatzacoalcos, Veracruz'),
('LIV-EXPRESS-3-LAN','Liverpool Express Arandas - LANCOME','lancome','OC','Arandas, Jalisco'),
('LIV-EXPRESS-3-YSL','Liverpool Express Arandas - YSL','ysl','OC','Arandas, Jalisco'),
('LIV-GUADALAJ-LAN','Liverpool Guadalajara Centro - LANCOME','lancome','OC','Guadalajara, Jalisco'),
('LIV-GUADALAJ-YSL','Liverpool Guadalajara Centro - YSL','ysl','OC','Guadalajara, Jalisco'),
('LIV-POLANCO-LAN','Liverpool Polanco - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-POLANCO-YSL','Liverpool Polanco - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-SATELITE-LAN','Liverpool Satélite - LANCOME','lancome','CE','Naucalpan, Estado de México'),
('LIV-SATELITE-YSL','Liverpool Satélite - YSL','ysl','CE','Naucalpan, Estado de México'),
('LIV-CORDOBA--LAN','Liverpool Córdoba Crystal - LANCOME','lancome','SE','Córdoba, Veracruz'),
('LIV-CORDOBA--YSL','Liverpool Córdoba Crystal - YSL','ysl','SE','Córdoba, Veracruz'),
('LIV-GALERIAS22-LAN','Liverpool Galerías Santa Anita - LANCOME','lancome','OC','Tlajomulco, Jalisco'),
('LIV-GALERIAS22-YSL','Liverpool Galerías Santa Anita - YSL','ysl','OC','Tlajomulco, Jalisco'),
('LIV-GALERIAS23-LAN','Liverpool Galerías Toluca - LANCOME','lancome','CE','Toluca, Estado de México'),
('LIV-GALERIAS23-YSL','Liverpool Galerías Toluca - YSL','ysl','CE','Toluca, Estado de México'),
('LIV-PLAZA-PA-LAN','Liverpool Plaza Patria - LANCOME','lancome','OC','Zapopan, Jalisco'),
('LIV-PLAZA-PA-YSL','Liverpool Plaza Patria - YSL','ysl','OC','Zapopan, Jalisco'),
('LIV-SANTA-FE-LAN','Liverpool Santa Fe - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-SANTA-FE-YSL','Liverpool Santa Fe - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-POZA-RIC-LAN','Liverpool Poza Rica - LANCOME','lancome','SE','Poza Rica, Veracruz'),
('LIV-POZA-RIC-YSL','Liverpool Poza Rica - YSL','ysl','SE','Poza Rica, Veracruz'),
('LIV-TECAMAC-LAN','Liverpool Tecámac - LANCOME','lancome','CE','Tecámac, Estado de México'),
('LIV-TECAMAC-YSL','Liverpool Tecámac - YSL','ysl','CE','Tecámac, Estado de México'),
('LIV-TEZONTLE-LAN','Liverpool Tezontle - LANCOME','lancome','CE','Ciudad de México, CDMX'),
('LIV-TEZONTLE-YSL','Liverpool Tezontle - YSL','ysl','CE','Ciudad de México, CDMX'),
('LIV-VERACRUZ3-LAN','Liverpool Veracruz Mocambo - LANCOME','lancome','SE','Boca del Río, Veracruz'),
('LIV-VERACRUZ3-YSL','Liverpool Veracruz Mocambo - YSL','ysl','SE','Boca del Río, Veracruz'),
('LIV-COACALCO-LAN','Liverpool Coacalco - LANCOME','lancome','CE','Coacalco, Estado de México'),
('LIV-COACALCO-YSL','Liverpool Coacalco - YSL','ysl','CE','Coacalco, Estado de México'),
('LIV-COACALCO2-LAN','Liverpool Coacalco (2) - LANCOME','lancome','CE','Coacalco, Estado de México'),
('LIV-COACALCO2-YSL','Liverpool Coacalco (2) - YSL','ysl','CE','Coacalco, Estado de México'),
('LIV-MONCLOVA-LAN','Liverpool Monclova - LANCOME','lancome','NE','Monclova, Coahuila'),
('LIV-MONCLOVA-YSL','Liverpool Monclova - YSL','ysl','NE','Monclova, Coahuila'),
('LIV-XALAPA-P2-LAN','Liverpool Xalapa Plaza Crystal - LANCOME','lancome','SE','Xalapa, Veracruz'),
('LIV-XALAPA-P2-YSL','Liverpool Xalapa Plaza Crystal - YSL','ysl','SE','Xalapa, Veracruz'),
('LIV-TIJUANA-LAN','Liverpool Tijuana - LANCOME','lancome','NO','Tijuana, Baja California'),
('LIV-TIJUANA-YSL','Liverpool Tijuana - YSL','ysl','NO','Tijuana, Baja California')
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name,region_code=EXCLUDED.region_code,address=EXCLUDED.address,active=true;

-- Remap demo data from old PH-POL-* to new PH-POLANC-*
UPDATE consumers SET store_id='PH-POLANC-LAN' WHERE store_id='PH-POL-LAN';
UPDATE consumers SET store_id='PH-POLANC-YSL' WHERE store_id='PH-POL-YSL';
UPDATE purchases SET store_id='PH-POLANC-LAN' WHERE store_id='PH-POL-LAN';
UPDATE purchases SET store_id='PH-POLANC-YSL' WHERE store_id='PH-POL-YSL';
UPDATE appointments SET store_id='PH-POLANC-LAN' WHERE store_id='PH-POL-LAN';
UPDATE appointments SET store_id='PH-POLANC-YSL' WHERE store_id='PH-POL-YSL';
UPDATE visits SET store_id='PH-POLANC-LAN' WHERE store_id='PH-POL-LAN';
UPDATE visits SET store_id='PH-POLANC-YSL' WHERE store_id='PH-POL-YSL';
UPDATE profiles SET store_id='PH-POLANC-LAN' WHERE store_id='PH-POL-LAN';
UPDATE profiles SET store_id='PH-POLANC-YSL' WHERE store_id='PH-POL-YSL';
UPDATE profiles SET region='CE' WHERE region='CS';

-- Mark old demo stores not in new official list as inactive
UPDATE stores SET active=false
WHERE region_code IN ('CS','OR','NW','CN','SW')
  AND code NOT IN (SELECT DISTINCT store_id FROM consumers WHERE store_id IS NOT NULL
                   UNION SELECT DISTINCT store_id FROM purchases
                   UNION SELECT DISTINCT store_id FROM appointments
                   UNION SELECT DISTINCT store_id FROM visits);
