INSERT INTO public.stores (code,name,region_code,address,active,brand) VALUES
('PH-PALACIO_CENTRO','Palacio Centro','CE','Ciudad de México, CDMX',true,NULL),
('PH-PALACIO_COYOACAN','Palacio Coyoacán','CE','Ciudad de México, CDMX',true,NULL),
('PH-PALACIO_DURANGO','Palacio Durango','CE','Ciudad de México, CDMX',true,NULL),
('PH-PALACIO_GUADALAJARA','Palacio Guadalajara','OC','Guadalajara, Jalisco',true,NULL),
('PH-PALACIO_INTERLOMAS','Palacio Interlomas','CE','Huixquilucan, Estado de México',true,NULL),
('PH-PALACIO_LEON','Palacio León','BA','León, Guanajuato',true,NULL),
('PH-PALACIO_MONTERREY','Palacio Monterrey','NE','Monterrey, Nuevo León',true,NULL),
('PH-PALACIO_PERISUR','Palacio Perisur','CE','Ciudad de México, CDMX',true,NULL),
('PH-PALACIO_POLANCO','Palacio Polanco','CE','Ciudad de México, CDMX',true,NULL),
('PH-PALACIO_PUEBLA','Palacio Puebla','CE','Puebla, Puebla',true,NULL),
('PH-PALACIO_QUERETARO','Palacio Querétaro','BA','Querétaro, Querétaro',true,NULL),
('PH-PALACIO_SANTA_FE','Palacio Santa Fe','CE','Ciudad de México, CDMX',true,NULL),
('PH-PALACIO_SATELITE','Palacio Satélite','CE','Naucalpan, Estado de México',true,NULL),
('PH-PALACIO_VERACRUZ','Palacio Veracruz','SE','Veracruz, Veracruz',true,NULL),
('PH-PALACIO_VILLAHERMOSA','Palacio Villahermosa','SE','Villahermosa, Tabasco',true,NULL),
('PH-LA_BOUTIQUE_PALACIO_CANCUN','La Boutique Palacio Cancún','SE','Cancún, Quintana Roo',true,NULL),
('PH-LA_BOUTIQUE_PALACIO_ACOXPA','La Boutique Palacio Acoxpa','CE','Ciudad de México, CDMX',true,NULL),
('PH-LA_BOUTIQUE_PALACIO_ACAPULCO','La Boutique Palacio Acapulco','SU','Acapulco, Guerrero',true,NULL),
('LIV-LIVERPOOL_GALERIAS_CUERNAVACA','Liverpool Galerías Cuernavaca','CE','Cuernavaca, Morelos',true,NULL),
('LIV-LIVERPOOL_ACAPULCO_LA_ISLA','Liverpool Acapulco La Isla','SU','Acapulco, Guerrero',true,NULL),
('LIV-LIVERPOOL_AGS_ALTARIA','Liverpool Ags. Altaria','BA','Aguascalientes, Aguascalientes',true,NULL),
('LIV-LIVERPOOL_ALTABRISA','Liverpool Altabrisa','SE','Mérida, Yucatán',true,NULL),
('LIV-LIVERPOOL_ANDARES','Liverpool Andares','OC','Zapopan, Jalisco',true,NULL),
('LIV-LIVERPOOL_ANGELOPOLIS','Liverpool Angelópolis','CE','Puebla, Puebla',true,NULL),
('LIV-LIVERPOOL_ANTEA','Liverpool Antea','BA','Querétaro, Querétaro',true,NULL),
('LIV-LIVERPOOL_ATLIXCO','Liverpool Atlixco','CE','Atlixco, Puebla',true,NULL),
('LIV-LIVERPOOL_CANCUN','Liverpool Cancún','SE','Cancún, Quintana Roo',true,NULL),
('LIV-LIVERPOOL_CD_JUAREZ_LAS_MISIONES','Liverpool Cd. Juárez Las Misiones','NO','Ciudad Juárez, Chihuahua',true,NULL),
('LIV-LIVERPOOL_CENTRO','Liverpool Centro','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_CIUDAD_VICTORIA','Liverpool Ciudad Victoria','NE','Ciudad Victoria, Tamaulipas',true,NULL),
('LIV-LIVERPOOL_COATZACOALCOS','Liverpool Coatzacoalcos','SE','Coatzacoalcos, Veracruz',true,NULL),
('LIV-LIVERPOOL_COLIMA','Liverpool Colima','OC','Colima, Colima',true,NULL),
('LIV-LIVERPOOL_CULIACAN','Liverpool Culiacán','NO','Culiacán, Sinaloa',true,NULL),
('LIV-LIVERPOOL_DURANGO','Liverpool Durango','NO','Durango, Durango',true,NULL),
('LIV-LIVERPOOL_FRESNILLO','Liverpool Fresnillo','BA','Fresnillo, Zacatecas',true,NULL),
('LIV-LIVERPOOL_GALERIAS_ATIZAPAN','Liverpool Galerías Atizapán','CE','Atizapán, Estado de México',true,NULL),
('LIV-LIVERPOOL_GALERIAS_CAMPECHE','Liverpool Galerías Campeche','SE','Campeche, Campeche',true,NULL),
('LIV-LIVERPOOL_GALERIAS_CELAYA','Liverpool Galerías Celaya','BA','Celaya, Guanajuato',true,NULL),
('LIV-LIVERPOOL_GALERIAS_CUERNAVACA-39','Liverpool Galerías Cuernavaca','CE','Cuernavaca, Morelos',true,NULL),
('LIV-LIVERPOOL_GALERIAS_HERMOSILLO','Liverpool Galerías Hermosillo','NO','Hermosillo, Sonora',true,NULL),
('LIV-LIVERPOOL_GALERIAS_MONTERREY','Liverpool Galerías Monterrey','NE','Monterrey, Nuevo León',true,NULL),
('LIV-LIVERPOOL_GALERIAS_MERIDA','Liverpool Galerías Mérida','SE','Mérida, Yucatán',true,NULL),
('LIV-LIVERPOOL_GALERIAS_SALTILLO','Liverpool Galerías Saltillo','NE','Saltillo, Coahuila',true,NULL),
('LIV-LIVERPOOL_GALERIAS_TABASCO','Liverpool Galerías Tabasco','SE','Villahermosa, Tabasco',true,NULL),
('LIV-LIVERPOOL_GALERIAS_ZACATECAS','Liverpool Galerías Zacatecas','BA','Zacatecas, Zacatecas',true,NULL),
('LIV-LIVERPOOL_HERMOSILLO_ENCINAS','Liverpool Hermosillo Encinas','NO','Hermosillo, Sonora',true,NULL),
('LIV-LIVERPOOL_LA_PAZ','Liverpool La Paz','NO','La Paz, Baja California Sur',true,NULL),
('LIV-LIVERPOOL_MAZATLAN_MARINA','Liverpool Mazatlán Marina','NO','Mazatlán, Sinaloa',true,NULL),
('LIV-LIVERPOOL_MEXICALI','Liverpool Mexicali','NO','Mexicali, Baja California',true,NULL),
('LIV-LIVERPOOL_MONTERREY_ESFERA','Liverpool Monterrey Esfera','NE','Monterrey, Nuevo León',true,NULL),
('LIV-LIVERPOOL_MORELIA_ALTOZANO','Liverpool Morelia Altozano','OC','Morelia, Michoacán',true,NULL),
('LIV-LIVERPOOL_MERIDA_LA_ISLA_CABO_NORTE','Liverpool Mérida la Isla Cabo Norte','SE','Mérida, Yucatán',true,NULL),
('LIV-LIVERPOOL_PACHUCA','Liverpool Pachuca','CE','Pachuca, Hidalgo',true,NULL),
('LIV-LIVERPOOL_PARQUE_LAS_ANTENAS','Liverpool Parque Las Antenas','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_PARQUE_PUEBLA','Liverpool Parque Puebla','CE','Puebla, Puebla',true,NULL),
('LIV-LIVERPOOL_PASEO_INTERLOMAS','Liverpool Paseo Interlomas','CE','Huixquilucan, Estado de México',true,NULL),
('LIV-LIVERPOOL_PASEO_INTERLOMAS_2','Liverpool Paseo Interlomas (2)','CE','Huixquilucan, Estado de México',true,NULL),
('LIV-LIVERPOOL_PASEO_QUERETARO','Liverpool Paseo Querétaro','BA','Querétaro, Querétaro',true,NULL),
('LIV-LIVERPOOL_SALINA_CRUZ','Liverpool Salina Cruz','SU','Salina Cruz, Oaxaca',true,NULL),
('LIV-LIVERPOOL_SAN_LUIS_POTOSI','Liverpool San Luis Potosí','BA','San Luis Potosí, San Luis Potosí',true,NULL),
('LIV-LIVERPOOL_TEPIC','Liverpool Tepic','OC','Tepic, Nayarit',true,NULL),
('LIV-LIVERPOOL_TLAXCALA','Liverpool Tlaxcala','CE','Tlaxcala, Tlaxcala',true,NULL),
('LIV-LIVERPOOL_TOREO','Liverpool Toreo','CE','Naucalpan, Estado de México',true,NULL),
('LIV-LIVERPOOL_TUXTLA','Liverpool Tuxtla','SU','Tuxtla Gutiérrez, Chiapas',true,NULL),
('LIV-LIVERPOOL_TUXTLA_ORIENTE','Liverpool Tuxtla Oriente','SU','Tuxtla Gutiérrez, Chiapas',true,NULL),
('LIV-LIVERPOOL_ZAMORA','Liverpool Zamora','OC','Zamora, Michoacán',true,NULL),
('LIV-LIVERPOOL_AGUASCALIENTES_VILLASUNCION','Liverpool Aguascalientes Villasunción','BA','Aguascalientes, Aguascalientes',true,NULL),
('LIV-LIVERPOOL_CD_JARDIN','Liverpool Cd. Jardín','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_CD_OBREGON','Liverpool Cd. Obregón','NO','Ciudad Obregón, Sonora',true,NULL),
('LIV-LIVERPOOL_CD_DEL_CARMEN','Liverpool Cd. del Carmen','SE','Ciudad del Carmen, Campeche',true,NULL),
('LIV-LIVERPOOL_CHETUMAL','Liverpool Chetumal','SE','Chetumal, Quintana Roo',true,NULL),
('LIV-LIVERPOOL_CHIHUAHUA_FASHION_MALL','Liverpool Chihuahua Fashion Mall','NO','Chihuahua, Chihuahua',true,NULL),
('LIV-LIVERPOOL_CUAUTLA','Liverpool Cuautla','CE','Cuautla, Morelos',true,NULL),
('LIV-LIVERPOOL_GALERIAS_CHILPANCINGO','Liverpool Galerías Chilpancingo','SU','Chilpancingo, Guerrero',true,NULL),
('LIV-LIVERPOOL_GALERIAS_COAPA','Liverpool Galerías Coapa','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_GALERIAS_GUADALAJARA','Liverpool Galerías Guadalajara','OC','Guadalajara, Jalisco',true,NULL),
('LIV-LIVERPOOL_GALERIAS_QUERETARO','Liverpool Galerías Querétaro','BA','Querétaro, Querétaro',true,NULL),
('LIV-LIVERPOOL_GALERIAS_SERDAN','Liverpool Galerías Serdán','CE','Puebla, Puebla',true,NULL),
('LIV-LIVERPOOL_IRAPUATO_PLAZA_CIBELES','Liverpool Irapuato Plaza Cibeles','BA','Irapuato, Guanajuato',true,NULL),
('LIV-LIVERPOOL_LA_PERLA','Liverpool La Perla','OC','Zapopan, Jalisco',true,NULL),
('LIV-LIVERPOOL_LOS_MOCHIS','Liverpool Los Mochis','NO','Los Mochis, Sinaloa',true,NULL),
('LIV-LIVERPOOL_MONTERREY_CENTRO','Liverpool Monterrey Centro','NE','Monterrey, Nuevo León',true,NULL),
('LIV-LIVERPOOL_MONTERREY_LA_FE','Liverpool Monterrey la Fe','NE','Monterrey, Nuevo León',true,NULL),
('LIV-LIVERPOOL_MORELIA_LAS_AMERICAS','Liverpool Morelia Las Américas','OC','Morelia, Michoacán',true,NULL),
('LIV-LIVERPOOL_OAXACA','Liverpool Oaxaca','SU','Oaxaca, Oaxaca',true,NULL),
('LIV-LIVERPOOL_OAXACA_PLAZA_BELLA','Liverpool Oaxaca Plaza Bella','SU','Oaxaca, Oaxaca',true,NULL),
('LIV-LIVERPOOL_ORIZABA','Liverpool Orizaba','SE','Orizaba, Veracruz',true,NULL),
('LIV-LIVERPOOL_SALAMANCA','Liverpool Salamanca','BA','Salamanca, Guanajuato',true,NULL),
('LIV-LIVERPOOL_SAN_LUIS_EL_DORADO','Liverpool San Luis El Dorado','BA','San Luis Potosí, San Luis Potosí',true,NULL),
('LIV-LIVERPOOL_TAMPICO','Liverpool Tampico','NE','Tampico, Tamaulipas',true,NULL),
('LIV-LIVERPOOL_TAMPICO_ALTAMA','Liverpool Tampico Altama','NE','Tampico, Tamaulipas',true,NULL),
('LIV-LIVERPOOL_TAPACHULA','Liverpool Tapachula','SU','Tapachula, Chiapas',true,NULL),
('LIV-LIVERPOOL_TEPIC_CENTRO','Liverpool Tepic Centro','OC','Tepic, Nayarit',true,NULL),
('LIV-LIVERPOOL_TLALNEPANTLA','Liverpool Tlalnepantla','CE','Tlalnepantla, Estado de México',true,NULL),
('LIV-LIVERPOOL_TORREON','Liverpool Torreón','NE','Torreón, Coahuila',true,NULL),
('LIV-LIVERPOOL_ACAPULCO_GALERIAS','Liverpool Acapulco Galerías','SU','Acapulco, Guerrero',true,NULL),
('LIV-LIVERPOOL_CD_JUAREZ_RIO_GRANDE','Liverpool Cd Juárez Rio Grande','NO','Ciudad Juárez, Chihuahua',true,NULL),
('LIV-LIVERPOOL_CHIHUAHUA_PRESIDENTES','Liverpool Chihuahua Presidentes','NO','Chihuahua, Chihuahua',true,NULL),
('LIV-LIVERPOOL_COMITAN','Liverpool Comitán','SU','Comitán, Chiapas',true,NULL),
('LIV-LIVERPOOL_GALERIAS_INSURGENTES','Liverpool Galerías Insurgentes','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_GALERIAS_PUERTO_VALLARTA','Liverpool Galerías Puerto Vallarta','OC','Puerto Vallarta, Jalisco',true,NULL),
('LIV-LIVERPOOL_GALERIAS_SAN_JUAN_DEL_RIO','Liverpool Galerías San Juan del Río','BA','San Juan del Río, Querétaro',true,NULL),
('LIV-LIVERPOOL_GUANAJUATO','Liverpool Guanajuato','BA','Guanajuato, Guanajuato',true,NULL),
('LIV-LIVERPOOL_LEON_ALTACIA','Liverpool León Altacia','BA','León, Guanajuato',true,NULL),
('LIV-LIVERPOOL_MITIKAH','Liverpool Mitikah','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_MONTERREY_CUMBRES','Liverpool Monterrey Cumbres','NE','Monterrey, Nuevo León',true,NULL),
('LIV-LIVERPOOL_PLAYA_DEL_CARMEN','Liverpool Playa del Carmen','SE','Playa del Carmen, Quintana Roo',true,NULL),
('LIV-LIVERPOOL_TEHUACAN','Liverpool Tehuacán','CE','Tehuacán, Puebla',true,NULL),
('LIV-LIVERPOOL_TUXPAN','Liverpool Tuxpan','SE','Tuxpan, Veracruz',true,NULL),
('LIV-LIVERPOOL_VILLAHERMOSA_CRYSTAL','Liverpool Villahermosa Crystal','SE','Villahermosa, Tabasco',true,NULL),
('LIV-LIVERPOOL_ECATEPEC','Liverpool Ecatepec','CE','Ecatepec, Estado de México',true,NULL),
('LIV-LIVERPOOL_LEON_PLAZA_MAYOR','Liverpool León Plaza Mayor','BA','León, Guanajuato',true,NULL),
('LIV-LIVERPOOL_LINDAVISTA','Liverpool Lindavista','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_LINDAVISTA_2','Liverpool Lindavista (2)','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_MAZATLAN_CENTRO','Liverpool Mazatlán Centro','NO','Mazatlán, Sinaloa',true,NULL),
('LIV-LIVERPOOL_MONTERREY_VALLE','Liverpool Monterrey Valle','NE','Monterrey, Nuevo León',true,NULL),
('LIV-LIVERPOOL_OBLATOS_GUADALAJARA','Liverpool Oblatos Guadalajara','OC','Guadalajara, Jalisco',true,NULL),
('LIV-LIVERPOOL_PUEBLA_CRYSTAL','Liverpool Puebla Crystal','CE','Puebla, Puebla',true,NULL),
('LIV-LIVERPOOL_TEPEYAC','Liverpool Tepeyac','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_VERACRUZ_EL_DORADO','Liverpool Veracruz El Dorado','SE','Veracruz, Veracruz',true,NULL),
('LIV-LIVERPOOL_EXPRESS_CD_GUZMAN','Liverpool Express Cd Guzmán','OC','Ciudad Guzmán, Jalisco',true,NULL),
('LIV-LIVERPOOL_EXPRESS_LAGOS_DE_MORENO','Liverpool Express Lagos de Moreno','OC','Lagos de Moreno, Jalisco',true,NULL),
('LIV-LIVERPOOL_GALERIAS_METEPEC','Liverpool Galerías Metepec','CE','Metepec, Estado de México',true,NULL),
('LIV-LIVERPOOL_PARQUE_DELTA','Liverpool Parque Delta','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_SAN_MIGUEL_DE_ALLENDE','Liverpool San Miguel de Allende','BA','San Miguel de Allende, Guanajuato',true,NULL),
('LIV-LIVERPOOL_TLAQUEPAQUE','Liverpool Tlaquepaque','OC','Tlaquepaque, Jalisco',true,NULL),
('LIV-LIVERPOOL_VERACRUZ_PLAZA_AMERICAS','Liverpool Veracruz Plaza Américas','SE','Veracruz, Veracruz',true,NULL),
('LIV-LIVERPOOL_GALERIAS_PERINORTE','Liverpool Galerías Perinorte','CE','Cuautitlán Izcalli, Estado de México',true,NULL),
('LIV-LIVERPOOL_GALERIAS_PERINORTE_2','Liverpool Galerías Perinorte (2)','CE','Cuautitlán Izcalli, Estado de México',true,NULL),
('LIV-LIVERPOOL_GRAN_PLAZA','Liverpool Gran Plaza','OC','Guadalajara, Jalisco',true,NULL),
('LIV-LIVERPOOL_PERISUR','Liverpool Perisur','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_XALAPA_PLAZA_AMERICAS','Liverpool Xalapa Plaza Américas','SE','Xalapa, Veracruz',true,NULL),
('LIV-LIVERPOOL_COATZACOALCOS_CRYSTAL','Liverpool Coatzacoalcos Crystal','SE','Coatzacoalcos, Veracruz',true,NULL),
('LIV-LIVERPOOL_EXPRESS_ARANDAS','Liverpool Express Arandas','OC','Arandas, Jalisco',true,NULL),
('LIV-LIVERPOOL_GUADALAJARA_CENTRO','Liverpool Guadalajara Centro','OC','Guadalajara, Jalisco',true,NULL),
('LIV-LIVERPOOL_POLANCO','Liverpool Polanco','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_SATELITE','Liverpool Satélite','CE','Naucalpan, Estado de México',true,NULL),
('LIV-LIVERPOOL_CORDOBA_CRYSTAL','Liverpool Córdoba Crystal','SE','Córdoba, Veracruz',true,NULL),
('LIV-LIVERPOOL_GALERIAS_SANTA_ANITA','Liverpool Galerías Santa Anita','OC','Tlajomulco, Jalisco',true,NULL),
('LIV-LIVERPOOL_GALERIAS_TOLUCA','Liverpool Galerías Toluca','CE','Toluca, Estado de México',true,NULL),
('LIV-LIVERPOOL_PLAZA_PATRIA','Liverpool Plaza Patria','OC','Zapopan, Jalisco',true,NULL),
('LIV-LIVERPOOL_SANTA_FE','Liverpool Santa Fe','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_POZA_RICA','Liverpool Poza Rica','SE','Poza Rica, Veracruz',true,NULL),
('LIV-LIVERPOOL_TECAMAC','Liverpool Tecámac','CE','Tecámac, Estado de México',true,NULL),
('LIV-LIVERPOOL_TEZONTLE','Liverpool Tezontle','CE','Ciudad de México, CDMX',true,NULL),
('LIV-LIVERPOOL_VERACRUZ_MOCAMBO','Liverpool Veracruz Mocambo','SE','Boca del Río, Veracruz',true,NULL),
('LIV-LIVERPOOL_COACALCO','Liverpool Coacalco','CE','Coacalco, Estado de México',true,NULL),
('LIV-LIVERPOOL_COACALCO_2','Liverpool Coacalco (2)','CE','Coacalco, Estado de México',true,NULL),
('LIV-LIVERPOOL_MONCLOVA','Liverpool Monclova','NE','Monclova, Coahuila',true,NULL),
('LIV-LIVERPOOL_XALAPA_PLAZA_CRYSTAL','Liverpool Xalapa Plaza Crystal','SE','Xalapa, Veracruz',true,NULL),
('LIV-LIVERPOOL_TIJUANA','Liverpool Tijuana','NO','Tijuana, Baja California',true,NULL)
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, region_code=EXCLUDED.region_code, address=EXCLUDED.address, active=true, brand=NULL;

UPDATE public.profiles SET store_id='PH-PALACIO_POLANCO' WHERE store_id IN ('PH-POLANC-LAN','PH-POLANC-YSL');
UPDATE public.consumers SET store_id='PH-PALACIO_POLANCO' WHERE store_id IN ('PH-POLANC-LAN','PH-POLANC-YSL');
UPDATE public.purchases SET store_id='PH-PALACIO_POLANCO' WHERE store_id IN ('PH-POLANC-LAN','PH-POLANC-YSL');
UPDATE public.appointments SET store_id='PH-PALACIO_POLANCO' WHERE store_id IN ('PH-POLANC-LAN','PH-POLANC-YSL');
UPDATE public.visits SET store_id='PH-PALACIO_POLANCO' WHERE store_id IN ('PH-POLANC-LAN','PH-POLANC-YSL');
UPDATE public.profiles SET store_id='PH-PALACIO_SANTA_FE' WHERE store_id='PH-SFE-LAN';
UPDATE public.consumers SET store_id='PH-PALACIO_SANTA_FE' WHERE store_id='PH-SFE-LAN';
UPDATE public.purchases SET store_id='PH-PALACIO_SANTA_FE' WHERE store_id='PH-SFE-LAN';
UPDATE public.profiles SET store_id='PH-PALACIO_MONTERREY' WHERE store_id='PH-MTY-LAN';
UPDATE public.consumers SET store_id='PH-PALACIO_MONTERREY' WHERE store_id='PH-MTY-LAN';
UPDATE public.purchases SET store_id='PH-PALACIO_MONTERREY' WHERE store_id='PH-MTY-LAN';
UPDATE public.profiles SET store_id='LIV-LIVERPOOL_POLANCO' WHERE store_id='LP-POL-LAN';
UPDATE public.consumers SET store_id='LIV-LIVERPOOL_POLANCO' WHERE store_id='LP-POL-LAN';
UPDATE public.purchases SET store_id='LIV-LIVERPOOL_POLANCO' WHERE store_id='LP-POL-LAN';

DELETE FROM public.stores WHERE code LIKE '%-LAN' OR code LIKE '%-YSL';